// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPS5uKrK1FG-8ymeTbZN4pdH3LA81Rtc0',
    appId: '1:584694130738:web:05cbf0c9dc21d991b2f42b',
    messagingSenderId: '584694130738',
    projectId: 'app-dev-quiz',
    authDomain: 'app-dev-quiz.firebaseapp.com',
    storageBucket: 'app-dev-quiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHcOGfmAVjn7P6sVTlBjUt66CHxF6Jw8g',
    appId: '1:584694130738:android:c448809b407ba919b2f42b',
    messagingSenderId: '584694130738',
    projectId: 'app-dev-quiz',
    storageBucket: 'app-dev-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFpe6QtLeAL_BLh2bG375W6knTMWotMys',
    appId: '1:584694130738:ios:22e82b224556c6f1b2f42b',
    messagingSenderId: '584694130738',
    projectId: 'app-dev-quiz',
    storageBucket: 'app-dev-quiz.appspot.com',
    iosClientId: '584694130738-jcafqfiku2vcsg0emh8q1dnn0f4ubtqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFpe6QtLeAL_BLh2bG375W6knTMWotMys',
    appId: '1:584694130738:ios:22e82b224556c6f1b2f42b',
    messagingSenderId: '584694130738',
    projectId: 'app-dev-quiz',
    storageBucket: 'app-dev-quiz.appspot.com',
    iosClientId: '584694130738-jcafqfiku2vcsg0emh8q1dnn0f4ubtqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
